[env:esp32-2432s028]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Libraries are pulled automatically by PlatformIO on first build
lib_deps =
  lovyan03/LovyanGFX @ ^1.1.10

build_flags =
  -D LGFX_USE_V1
  -D CORE_DEBUG_LEVEL=1

; Adjust flash speed/size if your module differs
upload_speed = 921600

; Filesystem for assets (logo.png)
board_build.filesystem = littlefs
 
